export type RegistrationStatus = "actif" | "suspendu" | "en_attente"

export const PROVINCES = [
  { code: "NKV", name: "Nord-Kivu" },
  { code: "SKV", name: "Sud-Kivu" },
]

export interface Vehicle {
  id: string
  // Plate
  plateProvince: string  // "KIN"
  plateDigits: string    // "1234"
  plateLetters: string   // "AA"
  plateYear: string      // "19" or "22"
  // Propriétaire
  owner: string
  address: string
  taxNumber: string
  // Véhicule
  usage: string
  firstCirculation: number
  // Technique
  make: string
  type: string
  chassisNumber: string
  engineNumber: string
  yearFabrication: number
  color: string
  fiscalPower: number
  // Statut
  status: RegistrationStatus
  nfcUid?: string
  registeredAt: string
}

export const mockVehicles: Vehicle[] = [
  {
    id: "VEH-001",
    plateProvince: "NKV",
    plateDigits: "0012",
    plateLetters: "AA",
    plateYear: "19",
    owner: "Mbeki Alain",
    address: "Av. Kasa-Vubu, N°14, Commune de Lingwala, Kinshasa",
    taxNumber: "A1234567B",
    usage: "Privé",
    firstCirculation: 2020,
    make: "Toyota",
    type: "Corolla",
    chassisNumber: "JTDBL40E099123456",
    engineNumber: "2ZR9834521",
    yearFabrication: 2019,
    color: "Blanc",
    fiscalPower: 7,
    status: "actif",
    nfcUid: "04:A3:2B:1F:9C:00",
    registeredAt: "10 jan. 2025",
  },
  {
    id: "VEH-002",
    plateProvince: "NKV",
    plateDigits: "0847",
    plateLetters: "AB",
    plateYear: "19",
    owner: "Société SAMBU SPRL",
    address: "Bd du 30 Juin, N°88, Commune de la Gombe, Kinshasa",
    taxNumber: "B9876543C",
    usage: "Commercial",
    firstCirculation: 2019,
    make: "Isuzu",
    type: "D-Max",
    chassisNumber: "IADTF8HS5K1234567",
    engineNumber: "4JJ1234567",
    yearFabrication: 2019,
    color: "Argent",
    fiscalPower: 11,
    status: "actif",
    nfcUid: "04:B7:4C:2E:AA:01",
    registeredAt: "09 jan. 2025",
  },
  {
    id: "VEH-003",
    plateProvince: "SKV",
    plateDigits: "1234",
    plateLetters: "AC",
    plateYear: "22",
    owner: "Lokuta Marie",
    address: "Av. des Huileries, N°7, Commune de Barumbu, Kinshasa",
    taxNumber: "C5544332D",
    usage: "Privé",
    firstCirculation: 2021,
    make: "Honda",
    type: "CR-V",
    chassisNumber: "5J6RM4H78ML012345",
    engineNumber: "K24W012345",
    yearFabrication: 2021,
    color: "Noir",
    fiscalPower: 8,
    status: "en_attente",
    registeredAt: "08 jan. 2025",
  },
  {
    id: "VEH-004",
    plateProvince: "NKV",
    plateDigits: "1456",
    plateLetters: "AD",
    plateYear: "19",
    owner: "Kabila Joseph",
    address: "Av. Pumbu, N°32, Commune de Ngaliema, Kinshasa",
    taxNumber: "D1122334E",
    usage: "Privé",
    firstCirculation: 2018,
    make: "Toyota",
    type: "Land Cruiser",
    chassisNumber: "JTMHX05J284012345",
    engineNumber: "1VD012345",
    yearFabrication: 2018,
    color: "Blanc",
    fiscalPower: 17,
    status: "actif",
    nfcUid: "04:C9:5D:3A:BB:02",
    registeredAt: "07 jan. 2025",
  },
  {
    id: "VEH-005",
    plateProvince: "SKV",
    plateDigits: "2098",
    plateLetters: "BA",
    plateYear: "22",
    owner: "Entreprise KONGO",
    address: "Zone Industrielle, Av. du Port, Matadi",
    taxNumber: "E6677889F",
    usage: "Commercial",
    firstCirculation: 2022,
    make: "Mercedes-Benz",
    type: "Sprinter 316",
    chassisNumber: "WDB9066351S123456",
    engineNumber: "OM651123456",
    yearFabrication: 2022,
    color: "Blanc",
    fiscalPower: 9,
    status: "suspendu",
    registeredAt: "06 jan. 2025",
  },
  {
    id: "VEH-006",
    plateProvince: "NKV",
    plateDigits: "2341",
    plateLetters: "AE",
    plateYear: "19",
    owner: "Mutombo André",
    address: "Av. Victoire, N°21, Commune de Lemba, Kinshasa",
    taxNumber: "F2233445G",
    usage: "Privé",
    firstCirculation: 2017,
    make: "Mitsubishi",
    type: "Pajero",
    chassisNumber: "V98WGVNKXHJ012345",
    engineNumber: "4M41012345",
    yearFabrication: 2016,
    color: "Gris",
    fiscalPower: 14,
    status: "actif",
    nfcUid: "04:D2:6E:4B:CC:03",
    registeredAt: "05 jan. 2025",
  },
  {
    id: "VEH-007",
    plateProvince: "NKV",
    plateDigits: "3567",
    plateLetters: "AF",
    plateYear: "19",
    owner: "ONG SANTÉ PLUS",
    address: "Av. Kabasele, N°5, Commune de Kintambo, Kinshasa",
    taxNumber: "G8899001H",
    usage: "Officiel",
    firstCirculation: 2023,
    make: "Toyota",
    type: "Hilux",
    chassisNumber: "MR0GX32G902345678",
    engineNumber: "2GD345678",
    yearFabrication: 2023,
    color: "Blanc",
    fiscalPower: 10,
    status: "actif",
    nfcUid: "04:E5:7F:5C:DD:04",
    registeredAt: "04 jan. 2025",
  },
  {
    id: "VEH-008",
    plateProvince: "SKV",
    plateDigits: "4890",
    plateLetters: "AG",
    plateYear: "22",
    owner: "Nkosi Bernard",
    address: "Av. des Cocotiers, N°9, Commune de Limete, Kinshasa",
    taxNumber: "H3344556I",
    usage: "Privé",
    firstCirculation: 2020,
    make: "Hyundai",
    type: "Tucson",
    chassisNumber: "KM8J3CA2XLU234567",
    engineNumber: "G4KD234567",
    yearFabrication: 2020,
    color: "Bleu",
    fiscalPower: 7,
    status: "actif",
    registeredAt: "03 jan. 2025",
  },
  {
    id: "VEH-009",
    plateProvince: "NKV",
    plateDigits: "5234",
    plateLetters: "AH",
    plateYear: "19",
    owner: "Transporteurs LUKUTU",
    address: "Av. Commerce, N°44, Commune de Kinshasa",
    taxNumber: "I5566778J",
    usage: "Commercial",
    firstCirculation: 2021,
    make: "Ford",
    type: "Transit",
    chassisNumber: "WF0EXXTTFE1234567",
    engineNumber: "TDCI1234567",
    yearFabrication: 2021,
    color: "Jaune",
    fiscalPower: 9,
    status: "actif",
    nfcUid: "04:F8:80:6D:EE:05",
    registeredAt: "02 jan. 2025",
  },
  {
    id: "VEH-010",
    plateProvince: "SKV",
    plateDigits: "7891",
    plateLetters: "AI",
    plateYear: "22",
    owner: "Ministère des Transports",
    address: "Immeuble ONATRA, Bd du 30 Juin, Kinshasa",
    taxNumber: "J0011223K",
    usage: "Officiel",
    firstCirculation: 2022,
    make: "Toyota",
    type: "Land Cruiser Prado",
    chassisNumber: "JTEBX9FJ90K345678",
    engineNumber: "1GR345678",
    yearFabrication: 2022,
    color: "Blanc",
    fiscalPower: 14,
    status: "actif",
    nfcUid: "04:A1:91:7E:FF:06",
    registeredAt: "31 déc. 2024",
  },
  {
    id: "VEH-011",
    plateProvince: "NKV",
    plateDigits: "3312",
    plateLetters: "AK",
    plateYear: "19",
    owner: "Bauma Christophe",
    address: "Av. Rutshuru, N°5, Commune de Ndosho, Goma",
    taxNumber: "K2233441L",
    usage: "Privé",
    firstCirculation: 2020,
    make: "Nissan",
    type: "Patrol",
    chassisNumber: "JN1WNYD21Z0123456",
    engineNumber: "TB48E123456",
    yearFabrication: 2019,
    color: "Noir",
    fiscalPower: 16,
    status: "actif",
    nfcUid: "04:B2:3C:4D:5E:07",
    registeredAt: "28 déc. 2024",
  },
  {
    id: "VEH-012",
    plateProvince: "NKV",
    plateDigits: "4420",
    plateLetters: "AL",
    plateYear: "19",
    owner: "SOCOGEKI SARL",
    address: "Av. du Lac, N°12, Goma, Nord-Kivu",
    taxNumber: "L3344552M",
    usage: "Commercial",
    firstCirculation: 2021,
    make: "Toyota",
    type: "Hiace",
    chassisNumber: "JTFSX22P900234567",
    engineNumber: "2TR234567",
    yearFabrication: 2021,
    color: "Blanc",
    fiscalPower: 9,
    status: "actif",
    registeredAt: "26 déc. 2024",
  },
  {
    id: "VEH-013",
    plateProvince: "SKV",
    plateDigits: "1870",
    plateLetters: "BB",
    plateYear: "22",
    owner: "Zawadi Honorine",
    address: "Av. Patrice Lumumba, N°3, Bukavu",
    taxNumber: "M4455663N",
    usage: "Privé",
    firstCirculation: 2019,
    make: "Suzuki",
    type: "Vitara",
    chassisNumber: "TSMMYD41S00345678",
    engineNumber: "M16A345678",
    yearFabrication: 2018,
    color: "Rouge",
    fiscalPower: 6,
    status: "en_attente",
    registeredAt: "24 déc. 2024",
  },
  {
    id: "VEH-014",
    plateProvince: "SKV",
    plateDigits: "6601",
    plateLetters: "BC",
    plateYear: "22",
    owner: "ONU-MONUSCO",
    address: "Base MONUSCO, Av. des Nations, Bukavu",
    taxNumber: "N5566774O",
    usage: "Officiel",
    firstCirculation: 2023,
    make: "Toyota",
    type: "Land Cruiser 300",
    chassisNumber: "JTMEB3FJ60K456789",
    engineNumber: "F33A456789",
    yearFabrication: 2023,
    color: "Blanc",
    fiscalPower: 18,
    status: "actif",
    nfcUid: "04:C3:4D:5E:6F:08",
    registeredAt: "22 déc. 2024",
  },
  {
    id: "VEH-015",
    plateProvince: "NKV",
    plateDigits: "5509",
    plateLetters: "AM",
    plateYear: "19",
    owner: "Paluku Serge",
    address: "Av. Himbi, N°18, Commune de Himbi, Goma",
    taxNumber: "O6677885P",
    usage: "Privé",
    firstCirculation: 2018,
    make: "Mitsubishi",
    type: "L200",
    chassisNumber: "MMBJNKB40HF567890",
    engineNumber: "4D56567890",
    yearFabrication: 2017,
    color: "Argent",
    fiscalPower: 10,
    status: "suspendu",
    registeredAt: "20 déc. 2024",
  },
]
